version: '2'
services:
  matches_db:
    image: mysql
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: apuesta
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: match
      MYSQL_HOST: matches_db
  teams_db:
    image: mongo
    ports:
      - "27017:27017"
  matches_ms:
    build: .
    command: bash -c "npm run sequelize db:migrate && npm run sequelize db:seed:all && npm start"
    ports:
      - "4003:4003"
    depends_on:
      - matches_db
      - teams_db
    environment:
      NODE_ENV: production
      PORT: 4003
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: apuesta
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: match
      MYSQL_HOST: matches_db
      MONGO_URL: mongodb://teams_db:27017/db
