version: '2'
services:
  matches_db:
    image: mysql
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: apuesta
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: match
      MYSQL_HOST: matches_db
  matches_ms:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    depends_on:
      - matches_db
    environment:
      NODE_ENV: production
      PORT: 4003
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: apuesta
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: match
      MYSQL_HOST: matches_db
