'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    // 

    return queryInterface.bulkInsert('Matches', [
      {
        id: 1,
        team_local_id: 'Rusia',
        team_visitor_id: 'Arabia Saudita',
        date: new Date(2018, 5, 14, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        team_local_id: 'Egipto',
        team_visitor_id: 'Uruguay',
        date: new Date(2018, 5, 15, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        team_local_id: 'Marruecos',
        team_visitor_id: 'Irán',
        date: new Date(2018, 5, 15, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        team_local_id: 'Portugal',
        team_visitor_id: 'España',
        date: new Date(2018, 5, 15, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        team_local_id: 'Francia',
        team_visitor_id: 'Australia',
        date: new Date(2018, 5, 16, 5),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        team_local_id: 'Argentina',
        team_visitor_id: 'Islandia',
        date: new Date(2018, 5, 16, 8),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        team_local_id: 'Perú',
        team_visitor_id: 'Dinamarca',
        date: new Date(2018, 5, 16, 11),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        team_local_id: 'Croacia',
        team_visitor_id: 'Nigeria',
        date: new Date(2018, 5, 16, 14),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        team_local_id: 'Costa Rica',
        team_visitor_id: 'Serbia',
        date: new Date(2018, 5, 17, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        team_local_id: 'Alemania',
        team_visitor_id: 'México',
        date: new Date(2018, 5, 17, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        team_local_id: 'Brasil',
        team_visitor_id: 'Suiza',
        date: new Date(2018, 5, 17, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        team_local_id: 'Suecia',
        team_visitor_id: 'República de Corea',
        date: new Date(2018, 5, 18, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        team_local_id: 'Bélgica',
        team_visitor_id: 'Panamá',
        date: new Date(2018, 5, 18, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        team_local_id: 'Túnez',
        team_visitor_id: 'Inglaterra',
        date: new Date(2018, 5, 18, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        team_local_id: 'Colombia',
        team_visitor_id: 'Japón',
        date: new Date(2018, 5, 19, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        team_local_id: 'Polonia',
        team_visitor_id: 'Senegal',
        date: new Date(2018, 5, 19, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        team_local_id: 'Rusia',
        team_visitor_id: 'Egipto',
        date: new Date(2018, 5, 19, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        team_local_id: 'Portugal',
        team_visitor_id: 'Marruecos',
        date: new Date(2018, 5, 20, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        team_local_id: 'Uruguay',
        team_visitor_id: 'Arabia Saudita',
        date: new Date(2018, 5, 20, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        team_local_id: 'Irán',
        team_visitor_id: 'España',
        date: new Date(2018, 5, 20, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 21,
        team_local_id: 'Dinamarca',
        team_visitor_id: 'Australia',
        date: new Date(2018, 5, 21, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 22,
        team_local_id: 'Francia',
        team_visitor_id: 'Perú',
        date: new Date(2018, 5, 21, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 23,
        team_local_id: 'Argentina',
        team_visitor_id: 'Croacia',
        date: new Date(2018, 5, 21, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 24,
        team_local_id: 'Brasil',
        team_visitor_id: 'Costa Rica',
        date: new Date(2018, 5, 22, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 25,
        team_local_id: 'Nigeria',
        team_visitor_id: 'Islandia',
        date: new Date(2018, 5, 22, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 26,
        team_local_id: 'Serbia',
        team_visitor_id: 'Suiza',
        date: new Date(2018, 5, 22, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 27,
        team_local_id: 'Bélgica',
        team_visitor_id: 'Túnez',
        date: new Date(2018, 5, 23, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 28,
        team_local_id: 'República de Corea',
        team_visitor_id: 'México',
        date: new Date(2018, 5, 23, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 29,
        team_local_id: 'Alemania',
        team_visitor_id: 'Suecia',
        date: new Date(2018, 5, 23, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 30,
        team_local_id: 'Inglaterra',
        team_visitor_id: 'Panamá',
        date: new Date(2018, 5, 24, 7),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 31,
        team_local_id: 'Japón',
        team_visitor_id: 'Senegal',
        date: new Date(2018, 5, 24, 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 32,
        team_local_id: 'Polonia',
        team_visitor_id: 'Colombia',
        date: new Date(2018, 5, 24, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 33,
        team_local_id: 'Uruguay',
        team_visitor_id: 'Rusia',
        date: new Date(2018, 5, 25, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 34,
        team_local_id: 'Arabia Saudita',
        team_visitor_id: 'Egipto',
        date: new Date(2018, 5, 25, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 35,
        team_local_id: 'Irán',
        team_visitor_id: 'Portugal',
        date: new Date(2018, 5, 25, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 36,
        team_local_id: 'España',
        team_visitor_id: 'Marruecos',
        date: new Date(2018, 5, 25, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 37,
        team_local_id: 'Dinamarca',
        team_visitor_id: 'Francia',
        date: new Date(2018, 5, 26, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 38,
        team_local_id: 'Australia',
        team_visitor_id: 'Perú',
        date: new Date(2018, 5, 26, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 39,
        team_local_id: 'Nigeria',
        team_visitor_id: 'Argentina',
        date: new Date(2018, 5, 26, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 40,
        team_local_id: 'Islandia',
        team_visitor_id: 'Croacia',
        date: new Date(2018, 5, 26, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 41,
        team_local_id: 'México',
        team_visitor_id: 'Suecia',
        date: new Date(2018, 5, 27, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 42,
        team_local_id: 'República de Corea',
        team_visitor_id: 'Alemania',
        date: new Date(2018, 5, 27, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 43,
        team_local_id: 'República de Corea',
        team_visitor_id: 'Alemania',
        date: new Date(2018, 5, 27, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 44,
        team_local_id: 'Serbia',
        team_visitor_id: 'Brasil',
        date: new Date(2018, 5, 27, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 45,
        team_local_id: 'Suiza',
        team_visitor_id: 'Costa Rica',
        date: new Date(2018, 5, 27, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 46,
        team_local_id: 'Japón',
        team_visitor_id: 'Polonia',
        date: new Date(2018, 5, 28, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 47,
        team_local_id: 'Senegal',
        team_visitor_id: 'Colombia',
        date: new Date(2018, 5, 28, 9),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 48,
        team_local_id: 'Panamá',
        team_visitor_id: 'Túnez',
        date: new Date(2018, 5, 28, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 49,
        team_local_id: 'Inglaterra',
        team_visitor_id: 'Bélgica',
        date: new Date(2018, 5, 28, 13),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.
    */
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('Person', null, {});
    */
  }
};
